In [2]:
import tensorflow as tf

In [4]:
q = tf.constant([[[0.9, 0.1],[0.6,0.4],[0.2,0.8]], [[0.5,0.5], [0.3, 0.7], [0.8, 0.2]]])
q

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[0.9, 0.1],
        [0.6, 0.4],
        [0.2, 0.8]],

       [[0.5, 0.5],
        [0.3, 0.7],
        [0.8, 0.2]]], dtype=float32)>

In [5]:
a = tf.constant([[[5, 1/5], [4, 1/4], [6,1/6]], [[3, 1/3], [2, 1/2], [1.5, 1/1.5]]])
a

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[5.        , 0.2       ],
        [4.        , 0.25      ],
        [6.        , 0.16666667]],

       [[3.        , 0.33333334],
        [2.        , 0.5       ],
        [1.5       , 0.6666667 ]]], dtype=float32)>

In [13]:
oneVec = tf.constant([1.0, 1.0])
largeQ = tf.transpose(tf.tensordot(q, oneVec, axes=0), perm=(0,1,3,2))
largeQ

<tf.Tensor: shape=(2, 3, 2, 2), dtype=float32, numpy=
array([[[[0.9, 0.1],
         [0.9, 0.1]],

        [[0.6, 0.4],
         [0.6, 0.4]],

        [[0.2, 0.8],
         [0.2, 0.8]]],


       [[[0.5, 0.5],
         [0.5, 0.5]],

        [[0.3, 0.7],
         [0.3, 0.7]],

        [[0.8, 0.2],
         [0.8, 0.2]]]], dtype=float32)>

In [16]:
pseul = tf.slice(q, [0,0,1], [-1, -1, 1])
pseul

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[0.1],
        [0.4],
        [0.8]],

       [[0.5],
        [0.7],
        [0.2]]], dtype=float32)>

In [25]:
ligne1 = tf.expand_dims(tf.concat((pseul, tf.ones((2,3,1))), axis=-1), axis=2)
ligne2 = tf.expand_dims(tf.concat((1-pseul, tf.zeros((2,3,1))), axis=-1), axis=2)
tf.concat((ligne1, ligne2), axis=2)

<tf.Tensor: shape=(2, 3, 2, 2), dtype=float32, numpy=
array([[[[0.1       , 1.        ],
         [0.9       , 0.        ]],

        [[0.4       , 1.        ],
         [0.6       , 0.        ]],

        [[0.8       , 1.        ],
         [0.19999999, 0.        ]]],


       [[[0.5       , 1.        ],
         [0.5       , 0.        ]],

        [[0.7       , 1.        ],
         [0.3       , 0.        ]],

        [[0.2       , 1.        ],
         [0.8       , 0.        ]]]], dtype=float32)>